### ISSUE TITLE
hai can i ask 

### ISSUE THREAD

**Issue by ainulSahira** [Hitesh297/laravel-admin-CMS#1]

**Comment by ainulSahira** [comment]
![Screenshot 2023-03-10 103741](https://user-images.githubusercontent.com/105167210/224209082-efe69eaa-defd-4e36-975a-796844b3f6a2.png)
what your admin email and password because i can't opened it, and i not find register file for email and password..if i add on mysql, still cannot use

**Comment by Hitesh297** [comment]
![portfolio seed user](https://github.com/Hitesh297/laravel-admin-CMS/assets/23136089/a85bd410-6681-4b33-ba7a-d1b38dfcaa25)

we have created users with password as password, while seeding.
